Adding entrypoint to add or remove ipv[46] from the nginx config
openspeedtest/Docker-Image pull request #2
Opened 2022-12-17 20:41 UTC by redrac

2022-12-17 23:23 UTC, openspeedtest requested changes

2022-12-17 23:23 UTC, openspeedtest commented on files/entrypoint.sh
> +  sed -i '/listen \[::\]:300/d' ${CONFIG}
This will work for both ports?
We have 3000 and 3001

 listen [::]:3000;
 listen [::]:3001 ssl;

````
  sed -i '/listen 3000/d' ${CONFIG}
  sed -i '/listen 3001 ssl/d' ${CONFIG}
````
I have not tested this.

2022-12-17 23:43 UTC, openspeedtest commented on files/entrypoint.sh
> +  sed -i '/listen \[::\]:300/d' ${CONFIG}
oh, this will replace 3000 and 3001 lines right.

2022-12-17 23:50 UTC, merged

2022-12-18 00:52 UTC, redrac commented on files/entrypoint.sh
> +  sed -i '/listen \[::\]:300/d' ${CONFIG}
It removes the lines, but yes it will work for 3000 and 3001. This way you don't have to mange two config files (one for ipv4 and one for ipv6) with the same config settings; just remove the irrelevant lines from the shared config.

2022-12-18 03:34 UTC, openspeedtest commented on files/entrypoint.sh
> +  sed -i '/listen \[::\]:300/d' ${CONFIG}
Image updated! Thankyou.

2023-06-03 07:08 UTC, openspeedtest commented
@redrac @bt90 

This version is in the Beta phase, so it is intended for testing purposes only.

````
sudo docker run -e ENABLE_SSL=True -e DOMAIN_NAME=example.com -e USER_EMAIL=you@example.com --restart=unless-stopped --name openspeedtest -d -p 80:3000 -p 443:3001 openspeedtest/beta:v1
````